---
title: "Homework 5"
author: "Corey Maxedon, Joe Stoica, Austin Lesh"
date: "10/21/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Link to GitHub Repo: https://github.com/coreymaxedon/hw5

## Question 1

The commit history has three commits. One with the initial commit of the blank files. One with updated llr_functions.R and test_llr.R files. One with an updated benchmark_llr.R file. We have one branch called master that is pointing to the last commit. The HEAD is pointing to master.

## Question 2 (the first time)

After creating a new branch, HEAD is pointing to speed-test-1. After making changes, the master will point to the older commit, while speed-test-1 will point to the new commit that contains our new changes. 

## Question 2 (the second time)

We used apply and separated by column. Since only the diagonal of Wz has numbers, this is equalivalent to each element of a Wz vector (diagonal values of original Wz) being multiplied by each row of X and y. 

## Question 3

The new version is much faster. The speed-test-1 version cut the median time in half.

## Question 4

We used sweep and the * operator. Sweep works like apply. * multiples element by element of each vector. This works the same since Wz was originally just a diagonal matrix. The other numbers would be zero except the piece of X or y multiplied by the diagonal element.

## Question 5

The fastest version was speed-test-2. The speed up over speed-test-1 was pretty marginal. Essentially, the same operation is happening in a slightly different way. We also did speed-test-extra. We realized the * operator would recycle Wz in Wz * X. Surprisely, speed-test-2 was still the fastest.

Results:
**Master:**
Unit: milliseconds
                     expr      min       lq     mean  median       uq      max neval
source("llr_functions.R") 452.1253 467.8461 596.8217 501.992 619.4566 1977.729   100

**speed-test-1:**
                     expr      min       lq     mean   median       uq     max neval
source("llr_functions.R") 221.8562 241.0305 291.3232 252.2806 336.5498 893.165   100

 
**speed-test-2**
                      expr      min       lq     mean   median       uq      max neval)
 source("llr_functions.R") 209.3638 221.2804 273.8552 229.4321 320.9144 787.7929   100

## Question 6

We get a timeline of commit on each branch. This gave the history of every commit on every branch including the time the commit was done and who committed the update. The comment was also included.
